# Generated by Django 5.0.6 on 2024-07-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mixer', 'mixer'), ('turntable', 'turntable'), ('headphones', 'headphones'), ('amplifier', 'amplifier'), ('speaker', 'speaker'), ('other', 'other')], default='other', max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ready', 'ready'), ('in_rent', 'in_rent'), ('booked', 'booked'), ('faulty', 'faulty'), ('lost', 'lost')], default='ready', max_length=100)),
                ('warehouse_place', models.IntegerField(default=0)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
