# Generated by Django 5.0.6 on 2024-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warehouse_place',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
