# Generated by Django 5.0.6 on 2024-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrental', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='warehouse_place',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
