# Generated by Django 5.0.6 on 2024-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrental', '0005_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
