# Generated by Django 5.0.6 on 2024-07-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentrental', '0006_alter_booked_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
